version: '3.6'

services:
  torchserve_qa:
    image: torchserve_prototype:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    # instead of putting the models in image at build time, it is possible to
    # create a volume at runtime containing a folder with .mar models
    #volumes:
    #  - "./model-store:/home/model-server/model-store"
    container_name: torchserve_prototype

