name: Manual Builder
on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_MODELS:
        required: true
        default: 'pt_br:1.0=URL'
        description: 'model_name:version=url|...'
      image_name:
        required: true
        description: 'Image name'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: CI
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bothubit/bothub-nlp:${{ github.event.inputs.image_name }}
          no-cache: true
          build-args: |
            DOWNLOAD_MODELS=${{ github.event.inputs.DOWNLOAD_MODELS }}
